//Oliver
using UnityEngine;

public class EquipmentManager : MonoBehaviour
{
    [SerializeField] public GameObject AR;
    [SerializeField]public GameObject Pistole;
    [SerializeField]public GameObject Verband;
    [SerializeField]public GameObject Knife;
    public bool ARisOn = true;
    public bool PistoleIsOn = false;
    public bool VerbandIsOn = false;
    public bool KnifeIsOn = false;
    void Start()
    {
     
    }

    // Update is called once per frame
    void Update()
    {
        if(Input.GetKeyDown(KeyCode.Alpha2) && PistoleIsOn == false)
        {
            AR.SetActive(false);
            Pistole.SetActive(true);
            Verband.SetActive(false);
            Knife.SetActive(false);
            ARisOn = false;
            PistoleIsOn = true;
            VerbandIsOn = false;
            KnifeIsOn = false;
}
        if (Input.GetKeyDown(KeyCode.Alpha1) && ARisOn == false)
        {
            AR.SetActive(true);
            Pistole.SetActive(false);
            Verband.SetActive(false);
            Knife.SetActive(false);
            ARisOn = true;
            PistoleIsOn = false;
            VerbandIsOn = false;
            KnifeIsOn = false;

        }
        if (Input.GetKeyDown(KeyCode.Alpha3) && VerbandIsOn == false)
        {
            AR.SetActive(false);
            Pistole.SetActive(false);
            Verband.SetActive(true);
            Knife.SetActive(false);
            ARisOn = false;
            PistoleIsOn = false;
            VerbandIsOn = true;
            KnifeIsOn = false;

        }
        if (Input.GetKeyDown(KeyCode.Alpha4) && KnifeIsOn == false)
        {
            AR.SetActive(false);
            Pistole.SetActive(false);
            Verband.SetActive(false);
            Knife.SetActive(true);
            ARisOn = false;
            PistoleIsOn = false;
            VerbandIsOn = false;
            KnifeIsOn = true;

        }
    }
}
